project:
  type: website
  output-dir: docs

website:
  title: "westlab_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Research
        menu:
          - text: Green Heron Ecology
            href: green-heron.html
          - text: Red-headed Woodpecker Ecology
            href: red-headed-woodpecker.html
          - text: Sounds of Nature MN
            href: sounds-of-nature.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

